site_name: FastAPI-motor-oil
repo_name: volfpeter/fastapi-motor-oil
repo_url: https://github.com/volfpeter/fastapi-motor-oil

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight

plugins:
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          paths: [.]

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - index.md
  - Examples:
      - FastAPI: fastapi-example.md
  - API Reference:
      - api-service.md
      - api-model.md
      - api-delete-rule.md
      - api-validator.md
      - api-typing.md
      - api-bound-method-wrapper.md
